FROM node:20-alpine

WORKDIR /

ADD /ui/.next/standalone /standalone
ADD /ui/public /standalone/public
ADD /ui/.next/static /standalone/.next/static

WORKDIR /standalone

CMD ["/bin/sh", "-c", "node server.js"]